### ISSUE TITLE
cons! and list! macros

### ISSUE THREAD

**Issue by zachmse** [contain-rs/cons-list#6]
Hello! I recently claimed the "cons" crate on crates.io with the intent of creating a simple immutable cons list and a few convenience macros. However, your library already implements all the features I envisioned except for the macros.

I would like to create two simple macros, `cons!` and `list!`. As you might expect, the `cons!` macro would prepend an item to the front of a cons list (e.g. `cons!(item, tail)`) or prepend an item in front of Nil (e.g. `cons!(item)`).

The `list!` macro would just be shorthand for creating a cons list (e.g. `list!(1, 2, 3, 4)`).

Would you want to incorporate these macros into the cons-list library? If so, I can create a pull request. Otherwise, would you be okay with me utilizing the cons-list library in the cons crate and just creating the macros in there? It is certainly not my intention to step on your toes or compete with your library, so if you prefer that I not utilize this library that is okay too.

Thank you for your time!

**Comment by clarfonthey** [comment]
This crate is currently in maintenance mode, so, those probably wouldn't be accepted, unfortunately. You can make them in your own crate, though!

**Comment by zachmse** [comment]
Ah, I didn't realize that. Thank you for the heads-up! I will go ahead and add these macros to my own crate then :)
